### ISSUE TITLE
(Optionally) use toolbar icon instead of address bar icon in Firefox

### ISSUE THREAD

**Issue by rugk** [tasn/webext-signed-pages#10]
For me the address bar icon is just always hidden behind the `…`. So maybe at least offer the user a toolbar icon instead?

**Comment by rugk** [comment]
Although I think this may be connected to https://github.com/tasn/webext-signed-pages/issues/11, because if the element is inactive, it is not shown.

**Edit:** Yes, that's it. Disabled elements are of course not shown in the address bar.

Anyway I leave this issue open, maybe some people like toolbar buttons more. I'd say you can just add the button. Users can configure it via the browser's "Customize…" menu and drag it away if they don't need it. (i.e. if possible, don't show it by default)

**Comment by tasn** [comment]
The reason why the screenshot is different than what you get is that the screenshot was taken with Chromium (though I'm also a Firefox user myself).
I initially made it a toolbar icon, but then I decided to make it an address bar icon because this way, it's only shown for websites that are configured to show. I think I like this behaviour better. I could potentially make this a configuration option though.

**Comment by rugk** [comment]
Yeah, I also like that behavior (when it works now). As said:
> Anyway I leave this issue open, maybe some people like toolbar buttons more.

**Comment by rugk** [comment]
Okay, I think no one wants such a thing. :wink:
