### ISSUE TITLE
Verify JavaScript only

### ISSUE THREAD

**Issue by rugk** [tasn/webext-signed-pages#7]
At PrivateBin (a secure pastebin with e2e crypto), we have a use case, where we want to allow server admins to customize the design/layout of the page, and only want to verify the integrity of the JavaScript, which may be the only thing, which can actually be malicious.

See https://github.com/PrivateBin/PrivateBin/issues/138 for details.

So we use SRI, but a good idea would be to verify the JavaScript/SRI hashes only. Would that be possible?

**Comment by tasn** [comment]
I was looking into doing something similar for a slightly different use case. I wanted to be able to verify only the content. That is, for example, verify a blog post was written by a certain author, without caring about the template of the page. Unfortunately, I think it's impossible to do.

The problem with verifying anything less than the whole page including everything, is that, depending on your use case, you may be very vulnerable.

Let's first take a look at verifying only external JS. The main problem would be that the page itself could have javascript there (or additional unverified external javascript) that can run and do whatever it wants, so this is obviously not safe.
Let's continue with this use case, and just disallow any embedded scripts in the page, or external, unverified javascript. We now have a problem that a malicious server could for example have a div overlay that when clicked triggers javascript. OK, let's assume we are good at this cat and mouse game and we managed to block all javascript other than the signed ones (though this would be very limiting and possibly unwanted, but for the sake of discussion, let's assume that). You know how the problem of CSS, or in general, a fake template.
For example, one can change the "save" button to be a form, rather than an ajax request (or if already a form, change the form url). This would mean that the raw data could now be sent to a remote server.
So essentially, allowing changing the HTML itself in any way opens you up to many issues.
Even if we assume the HTML is static, and we only let users theme with CSS, there could still be issues! For example, let's assume you put sha256 sums in a website, your public key, or an important announcement. You can trust them all, because supposedly the site is verified with PGP. However, using CSS you can just hide the relevant elements and replace them with alternatives that include your malicious versions.

This is why I verify the whole page an suggest using SRI even for CSS. HTML is very complex, so the attack surface is very wide.

As for your use case, I'd consider maybe shifting the trust to the people running the custom instance. I know this is not ideal, but this is one way to solve it, but obviously, it's not a real solution.

In summary, I don't think this can be solved in a way that actually helps your use case.

I'm closing it because I don't see a way to move forward with this, if you think I'm wrong, please reopen.

**Comment by rugk** [comment]
Okay, thanks for the detailed explanation. Indeed one may be able to correctly block all JS, with a CSP (which also needs to be verified then), but you are right that you may be able to use CSS to modify the page and do evil things, is also possible.

> As for your use case, I'd consider maybe shifting the trust to the people running the custom instance.

Actually we tried to move the trust away from them. That seems to be quite difficult though...

/cc @elrido

**Comment by tasn** [comment]
> Okay, thanks for the detailed explanation. Indeed one may be able to correctly block all JS, with a CSP (which also needs to be verified then), but you are right that you may be able to use CSS to modify the page and do evil things, is also possible.

True, I didn't think about just using CSP (and verifying it in the extension), that solves the cat and mouse game, but you still remain with HTML structure and CSS as problems.

> Actually we tried to move the trust away from them. That seems to be quite difficult though...

Yeah, what I said didn't make much sense in the context of this problem. Obviously the whole purpose is not trusting the people deploying it.

Another possible solution-non-solution would be to not allow users to change the HTML nor the CSS, but let them change a pre set list of images, some colours, or maybe even some limited CSS. Maybe there's even a list somewhere with "safe css" that you can allow.

Just thoughts.

**Comment by rugk** [comment]
Yeah, good thoughts, we'll consider them. Thanks.

**Comment by rugk** [comment]
BTW, here is a good example of why CSS alone can still be dangerous: [A keylogger in CSS](https://github.com/maxchehab/CSS-Keylogging)

**Comment by tasn** [comment]
Ha, yeah, I saw that one. Thanks for adding this info here though. It's a good reference. :)
